GET http://localhost:3000/api/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZjE1OTYzMGQwOWQ5OTI3NmM2MDgxZmYiLCJ1c2VybmFtZSI6Im5ld3VzZXIiLCJyb2xlIjoiY3VzdG9tZXIiLCJpYXQiOjE1OTUyNTA1ODMsImV4cCI6MTU5NTI1MDY0M30.EoIaOImkB1cxq0Lr67i5ohUPEc4HNvJPwHqoLB7rb5o


###

POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "username": "admin12131",
    "password" : "admin"
}

###

POST http://localhost:3000/api/auth/token
Content-Type: application/json
Cookie: refreshToken=


###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin"
}

###

DELETE http://localhost:3000/api/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJjcnlwdFRlc3QiLCJpYXQiOjE1OTQ2NTgwMjZ9.DQd0jV8S4ae6l7S7tlwm1WssDK03421lq2BvOem_J4A"
}
