GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTU5NDkyMzIzNiwiZXhwIjoxNTk0OTIzMjk2fQ.FX7DhXL3GZL5ciZh-VBEauXHABPPiuQcFDxMZv1Ot6s

###

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "admin1",
    "password" : "admin1"
}

###

POST http://localhost:3000/api/users/token
Content-Type: application/json
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluMSIsImlhdCI6MTU5NDkyMTE4NX0.zYKvXpyfjQzUvMcEoDwbwmHRv5PaBH5UurItvjniZ6c; Max-Age=3; Path=/; Expires=Thu, 16 Jul 2020 17:39:49 GMT; HttpOnly


###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "username" : "admin1",
    "password" : "admin1"
}

###

DELETE http://localhost:3000/api/users/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJjcnlwdFRlc3QiLCJpYXQiOjE1OTQ2NTgwMjZ9.DQd0jV8S4ae6l7S7tlwm1WssDK03421lq2BvOem_J4A"
}
